[package]
name = "qi-messaging"
description = ""
license-file = "LICENSE.txt"
repository = "https://github.com/nyibbang/libqi-rs"
version = "0.1.0-dev"
edition = "2021"
rust-version = "1.59"

[dependencies]
qi-types = { path = "../qi-types" }
qi-format = { path = "../qi-format" }
thiserror = "1.0.38"
num-derive = "0.3.3"
num-traits = "0.2.15"
bitflags = "1.3.2"
derive_more = "0.99.17"
serde = "1.0.152"
tokio-util = { version = "0.7.7", features = ["codec"] }
tokio = { version = "1.26.0", features = ["io-util", "sync"] }
bytes = "1.4.0"
futures = "0.3.27"
pin-project-lite = "0.2.9"
derive-new = "0.5.9"
tracing = "0.1.37"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.4.0", features = ["async_tokio"] }
pretty_assertions = "1.3.0"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros", "net"] }

[[bench]]
name = "dispatch_benchmark"
harness = false
