[package]
name = "qi-messaging"
description = ""

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures= { workspace = true }
qi-value = { path = "../qi-value" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serde_json = { workspace = true }
serde-value = { workspace = true }
tokio-test = { workspace = true }
