[workspace]
members = [
    "qi-value",
    "qi-macros",
    "qi-format",
    "qi-messaging",
    "qi-services",
    "qi",

    # examples/tests
    "examples",
    "tests-macros",
    # "qi-tools",
]
