[package]
name = "libqi-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "qi"

[dependencies]
bitflags = "1.3.2"
futures = "0.3.24"
num-derive = "0.3.3"
num-traits = "0.2.15"
thiserror = "1.0.36"

[dev-dependencies]
assert_matches = "1.5.0"
futures-test = "0.3.24"
