[package]
name = "qi-tools"
description = ""

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.0.0"
qi = { path = "../qi" }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[[bin]]
name = "qi-cli"
