[package]
name = "examples"

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

publish = false

[dev-dependencies]
qi = { path = "../qi" }
tokio = { workspace = true, features = ["rt", "signal"] }
clap = { version = "4.5.32", features = ["derive"] }
tracing-subscriber = "0.3.19"
tracing = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
anyhow = "1.0.97"

[[example]]
name = "client"
path = "client.rs"

[[example]]
name = "server"
path = "server.rs"
