[package]
name = "examples"

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

publish = false

[dev-dependencies]
qi = { path = "../qi" }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "signal"] }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[[example]]
name = "client"
path = "client.rs"

[[example]]
name = "server"
path = "server.rs"
