[package]
name = "tests-macros"

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

publish = false

[dependencies]
qi-macros = { path = "../qi-macros" }
qi-value = { path = "../qi-value" }
trybuild = "1.0.104"
assert_matches = "1.5.0"
syn = { version = "2.0.100", features = ["extra-traits"] }
pretty_assertions = "1.4.1"
