[package]
name = "qi-format"
description = "The `qi` binary format for values of the `qi` type system"

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
qi-value = { path = "../qi-value" }
serde-value = { workspace = true }
serde_with = { workspace = true }
