[package]
name = "qi-format"
description = "The `qi` binary format for values of the `qi` type system"
license-file = "LICENSE.txt"
repository = "https://github.com/nyibbang/libqi-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[dependencies]
qi-types = { path = "../qi-types" }
