[package]
name = "qi-value"
description = "Values of the `qi` type system"

license-file = "../LICENSE.txt"
repository = "https://github.com/nyibbang/libqi-rs"
version = "0.1.0-dev"
edition = "2021"
rust-version = "1.63"

[dependencies]
bytes = { version = "1.4.0", features = ["serde"] }
derive_more = "0.99.17"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.39"
ordered-float = { version = "3.4.0", features = ["serde"] }
derive-new = "0.5.9"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.3.0"
serde_test = "1.0.152"
serde-value = "0.7.0"
